---
title: "Display UKB DTI in CP and MDD"
author: "Hannah Casey"
date: "2023-11-16"
output: html_document
---

This markdown will details the steps taken to plot DTI results in chronic pain and depression in UK Biobank.

### Required software:

[Mango](https://mangoviewer.com)

[R](https://www.r-project.org/#:~:text=Getting%20Started,choose%20your%20preferred%20CRAN%20mirror.)

### Map standardized effect sizes to HEX colour codes

```{r setup, include=FALSE}
# Load in packages
library(dplyr)

# Read in results 
res_CP_MDD_brain_structure_all <- read.csv("/Users/hannahcasey/Desktop/PhD/projects/UKB_CP_MDD_brain_structure/output/CP_MDD_structure_assoc_all.csv",header=T)
res_CP_MDD_brain_structure_all$sample <- "All"

CP_MDD_structure_sex_interaction_all <- read.csv("/Users/hannahcasey/Desktop/PhD/projects/UKB_CP_MDD_brain_structure/output/CP_MDD_structure_sex_interaction_all.csv",header=T)
CP_MDD_structure_sex_interaction_all$sample <- "Sex Interaction"

CP_MDD_structure_sex_interaction_all <- CP_MDD_structure_sex_interaction_all %>%
  select(brain_phenotype, brain_structure_type, disorder, beta, sample)

res_CP_MDD_brain_structure_female <- read.csv("/Users/hannahcasey/Desktop/PhD/projects/UKB_CP_MDD_brain_structure/output/CP_MDD_structure_assoc_females.csv",header=T)
res_CP_MDD_brain_structure_female$sample <- "Female"

res_CP_MDD_brain_structure_male <- read.csv("/Users/hannahcasey/Desktop/PhD/projects/UKB_CP_MDD_brain_structure/output/CP_MDD_structure_assoc_males.csv",header=T)
res_CP_MDD_brain_structure_male$sample <- "Male"

res_CP_MDD_brain_structure <- rbind(res_CP_MDD_brain_structure_all, res_CP_MDD_brain_structure_female, res_CP_MDD_brain_structure_male)

res_CP_MDD_brain_structure <- res_CP_MDD_brain_structure %>%
  select(brain_phenotype, brain_structure_type, disorder, beta, sample) %>%
  rbind(CP_MDD_structure_sex_interaction_all)

## Create new columns to reformat brain phenotypes for plotting
res_CP_MDD_brain_structure$brain_phenotype_plot <-  gsub("MD", "MD in", res_CP_MDD_brain_structure$brain_phenotype)
res_CP_MDD_brain_structure$brain_phenotype_plot <- gsub("FA", "FA in", res_CP_MDD_brain_structure$brain_phenotype_plot)
res_CP_MDD_brain_structure$brain_phenotype_plot <- gsub("volume", "Volume of", res_CP_MDD_brain_structure$brain_phenotype_plot)
res_CP_MDD_brain_structure$brain_phenotype_plot <- gsub("area", "Area of", res_CP_MDD_brain_structure$brain_phenotype_plot)
res_CP_MDD_brain_structure$brain_phenotype_plot <- gsub("thickness", "Thickness of", res_CP_MDD_brain_structure$brain_phenotype_plot)
res_CP_MDD_brain_structure$brain_phenotype_plot <- gsub("sub_cortical_Volume", "Subcortical volume", res_CP_MDD_brain_structure$brain_phenotype_plot)
res_CP_MDD_brain_structure$brain_phenotype_plot <- gsub("_|[.]", " ", res_CP_MDD_brain_structure$brain_phenotype_plot)

## Get only indidual MD tract measures
res_CP_MDD_brain_structure_regional_MD_MDD <- res_CP_MDD_brain_structure[(res_CP_MDD_brain_structure$brain_structure_type == "MD Tracts") & (res_CP_MDD_brain_structure$disorder == "recurrent_depression"),]

res_CP_MDD_brain_structure_regional_MD_CP <- res_CP_MDD_brain_structure[(res_CP_MDD_brain_structure$brain_structure_type == "MD Tracts") & (res_CP_MDD_brain_structure$disorder == "chronic_pain"),]

## Get only individual FA tract measures
res_CP_MDD_brain_structure_regional_FA_MDD <- res_CP_MDD_brain_structure[(res_CP_MDD_brain_structure$brain_structure_type == "FA Tracts")  & (res_CP_MDD_brain_structure$disorder == "recurrent_depression"),]

res_CP_MDD_brain_structure_regional_FA_CP <- res_CP_MDD_brain_structure[(res_CP_MDD_brain_structure$brain_structure_type == "FA Tracts") & (res_CP_MDD_brain_structure$disorder == "chronic_pain"),]

## Get HEX colour to represent Beta scores of each tract in each sample
## MD in MDD
## Use n equally spaced breaks to assign each value to n-1 equal sized bins 
ii <- cut(res_CP_MDD_brain_structure_regional_MD_MDD$beta, breaks = seq(-0.1, 0.1, len = length(res_CP_MDD_brain_structure_regional_MD_MDD$beta)), 
          include.lowest = TRUE)
## Use bin indices, ii, to select color from vector of n-1 equally spaced colors
colours <- colorRampPalette(c("blue","white", "red"))(length(res_CP_MDD_brain_structure_regional_MD_MDD$beta))[ii]

res_CP_MDD_brain_structure_regional_MD_MDD$colour <- colours
res_CP_MDD_brain_structure_regional_MD_MDD <- res_CP_MDD_brain_structure_regional_MD_MDD %>%
  select(brain_phenotype, colour, sample, disorder, beta)


## MD in CP
ii <- cut(res_CP_MDD_brain_structure_regional_MD_CP$beta, breaks = seq(-0.1, 0.1, len = length(res_CP_MDD_brain_structure_regional_MD_CP$beta)), 
          include.lowest = TRUE)
colours <- colorRampPalette(c("blue","white", "red"))(length(res_CP_MDD_brain_structure_regional_MD_CP$beta))[ii]
res_CP_MDD_brain_structure_regional_MD_CP$colour <- colours
res_CP_MDD_brain_structure_regional_MD_CP <- res_CP_MDD_brain_structure_regional_MD_CP %>%
  select(brain_phenotype, colour, sample, disorder, beta)

## FA in MDD
ii <- cut(res_CP_MDD_brain_structure_regional_FA_MDD$beta, breaks = seq(-0.1, 0.1, len = length(res_CP_MDD_brain_structure_regional_FA_MDD$beta)), 
          include.lowest = TRUE)
colours <- colorRampPalette(c("blue","white", "red"))(length(res_CP_MDD_brain_structure_regional_FA_MDD$beta))[ii]
res_CP_MDD_brain_structure_regional_FA_MDD$colour <- colours
res_CP_MDD_brain_structure_regional_FA_MDD <- res_CP_MDD_brain_structure_regional_FA_MDD %>%
  select(brain_phenotype, colour, sample, disorder, beta)


## FA in CP
ii <- cut(res_CP_MDD_brain_structure_regional_FA_CP$beta, breaks = seq(-0.1, 0.1, len = length(res_CP_MDD_brain_structure_regional_FA_CP$beta)), 
          include.lowest = TRUE)
colours <- colorRampPalette(c("blue","white", "red"))(length(res_CP_MDD_brain_structure_regional_FA_CP$beta))[ii]
res_CP_MDD_brain_structure_regional_FA_CP$colour <- colours
res_CP_MDD_brain_structure_regional_FA_CP <- res_CP_MDD_brain_structure_regional_FA_CP %>%
  select(brain_phenotype, colour, sample, disorder, beta)

```

### Download AutoPtx v0.1.1 and ExBox6:

[https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/AutoPtx](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/AutoPtx)
[https://www.fmrib.ox.ac.uk/primers/intro_primer/ExBox6/IntroBox6.html](https://www.fmrib.ox.ac.uk/primers/intro_primer/ExBox6/IntroBox6.html)
### Run analysis 

### Display DTI tract effect sizes

In Mango:

1. Select 'Open' > select 'Open Image'... > select 'nodif_brain_mask.nii.gz' in 'Exbox6' folder (start window)

2. Select 'Image' > select 'Build Surface' (image window)

3.  Select 'Surface' > select 'Material...' > set to 0.7 transparency (surface window)

4. Select 'File' > select select 'Add Overlay...' > Choose NII file  (image window)

5. Select 'Shapes' > select 'Add Overlay...' (surface window)

6. Select 'Shapes' > toggle name of DTI tract > select 'Material...' > press 'Select Color' > input HEX number from dataframe above > select 'OK' > Change 'Overlay Search Distance' to 0 > uncheck 'Show Overlay Colors' > select 'OK'

7. Repeat steps 4-6 until all DTI tracts have been added. When 'Add Overlay...' greyed out, select 'Remove Overlays'.


